#!/data/data/com.termux/files/usr/bin/bash
set -e

echo "🖥️ Adding Forge bootstrap OS command"

mkdir -p packages/forge-core/src/commands

cat > packages/forge-core/src/commands/bootstrap.mjs <<'JS'
import { join } from "node:path";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { getForgePaths } from "../lib/paths.mjs";
import { section, ok, fail } from "../lib/logger.mjs";

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function writeFileIfMissing(path, content) {
  if (existsSync(path)) return false;
  ensureDir(join(path, ".."));
  writeFileSync(path, content);
  return true;
}

function bootstrapBookSmithOs(paths) {
  const osRoot = join(paths.aiftRoot, "BookSmith-Federation-OS");

  if (!existsSync(osRoot)) {
    fail(`BookSmith-Federation-OS not found at ${osRoot}`);
    process.exit(1);
  }

  section("BookSmith Federation OS");

  const dirs = [
    "apps/web-os/app/api/booksmith/run",
    "apps/web-os/components",
    "apps/web-os/lib",
    "apps/marketplace",
    "apps/node-agent",
    "packages/federation-core/src",
    "packages/storage-core/src",
    "packages/marketplace-core/src",
    "packages/wallet-core/src",
    "packages/booksmith-bridge/src",
    "packages/ui/src",
    "docs/roadmaps",
    "scripts"
  ];

  for (const dir of dirs) {
    ensureDir(join(osRoot, dir));
    ok(`dir ${dir}`);
  }

  writeFileIfMissing(
    join(osRoot, "docs/roadmaps/PHASE-0.2-WEB-OS-SHELL.md"),
    `# Phase 0.2 — Web OS Shell

Generated by AIFT Forge.

## Goal

Build the first functional BookSmith Federation OS desktop shell.

## Required surfaces

- Dashboard
- App Launcher
- AI Chat Dock
- System Health
- Roadmap
- Canon Intake
- BookSmith Bridge placeholder

## Canon Rule

User paste/upload = accepted canon.

AI output = proposed patch until approved.
`
  );

  ok("BookSmith OS Phase 0.2 folder scaffold complete.");
}

export function bootstrap(args = []) {
  const target = args[0];
  const name = args[1] ?? "booksmith";
  const paths = getForgePaths(import.meta.url);

  if (target !== "os") {
    console.log("Usage:");
    console.log("  aift-forge bootstrap os booksmith");
    process.exit(1);
  }

  if (name !== "booksmith") {
    fail(`Unknown OS bootstrap target: ${name}`);
    process.exit(1);
  }

  console.log("🖥️ AIFT Forge Bootstrap OS");
  bootstrapBookSmithOs(paths);
}
JS

python - <<'PY'
from pathlib import Path

p = Path("packages/forge-core/src/cli/index.mjs")
text = p.read_text()

if 'import { bootstrap } from "../commands/bootstrap.mjs";' not in text:
    last_imports = [line for line in text.splitlines() if line.startswith("import ")]
    last = last_imports[-1]
    text = text.replace(last, last + '\nimport { bootstrap } from "../commands/bootstrap.mjs";')

if 'console.log("  bootstrap' not in text:
    text = text.replace(
        'console.log("  help',
        'console.log("  bootstrap  Bootstrap federation systems");\n  console.log("  help'
    )

if 'case "bootstrap":' not in text:
    text = text.replace(
        '  case "help":',
        '  case "bootstrap":\n    bootstrap(process.argv.slice(3));\n    break;\n  case "help":'
    )

p.write_text(text)
PY

echo "✅ Bootstrap OS command added."
echo ""
echo "Test:"
echo "  aift-forge bootstrap os booksmith"
