#!/data/data/com.termux/files/usr/bin/bash
set -e

echo "🏗️ Adding Forge repository generator"

mkdir -p packages/forge-core/src/templates

cat > packages/forge-core/src/templates/repository-template.mjs <<'JS'
export function repositoryReadmeTemplate({ displayName, repoName }) {
  return `# ${displayName}

Generated by AIFT Forge.

## Role

Describe this repository's role in the AI Freedom Trust Federation.

## Status

Foundation scaffold.

## Local Development

\`\`\`bash
npm install
npm test
\`\`\`

## Repository Identity

- Repository: ${repoName}
- Runtime: local-first
- Public mirror: optional
`;
}

export function repositoryAgentsTemplate({ displayName }) {
  return `# ${displayName} Agent Instructions

This repository follows AI Freedom Trust Federation development rules.

## Core Rules

1. Preserve human authorship and approval.
2. Prefer local-first workflows.
3. Treat public GitHub as a mirror, not the permanent source of truth.
4. Keep manifests accurate.
5. Do not silently overwrite user canon.
`;
}

export function repositoryManifestTemplate({ repoName, displayName }) {
  return JSON.stringify(
    {
      schema: "aift.repository.manifest.v1",
      repo_id: repoName,
      name: displayName,
      role: "generated-federation-repository",
      status: "foundation",
      runtime_source_of_truth: "local-first",
      public_mirror: "github-optional",
      principles: [
        "local-first",
        "federation-ready",
        "portable-identity",
        "transparent-build-records",
        "human-governed"
      ],
      created_by: "aift-forge",
      updated_at: new Date().toISOString()
    },
    null,
    2
  ) + "\n";
}

export function repositoryPackageJsonTemplate({ repoName }) {
  return JSON.stringify(
    {
      name: repoName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        test: "node --test"
      }
    },
    null,
    2
  ) + "\n";
}

export function repositoryGitignoreTemplate() {
  return `node_modules
dist
build
coverage
.env
.env.*
.DS_Store
*.log
`;
}

export function repositoryLicenseTemplate() {
  return `This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial.
`;
}
JS

python - <<'PY'
from pathlib import Path

p = Path("packages/forge-core/src/commands/generate.mjs")
text = p.read_text()

import_line = 'import { repositoryReadmeTemplate, repositoryAgentsTemplate, repositoryManifestTemplate, repositoryPackageJsonTemplate, repositoryGitignoreTemplate, repositoryLicenseTemplate } from "../templates/repository-template.mjs";'
if import_line not in text:
    last_imports = [line for line in text.splitlines() if line.startswith("import ")]
    last = last_imports[-1]
    text = text.replace(last, last + "\n" + import_line)

if 'if (type === "repository" || type === "repo")' not in text:
    marker = '  if (type === "package") {'
    insert = r'''  if (type === "repository" || type === "repo") {
    const repoName = toKebabCase(name);
    const displayName = toPascalCase(name);
    const repoRoot = join(paths.aiftRoot, repoName);

    section("Generate Repository");
    console.log(`Repository: ${repoName}`);
    console.log(`Path: ${repoRoot}`);

    writeFileOnce(join(repoRoot, "README.md"), repositoryReadmeTemplate({ displayName, repoName }));
    writeFileOnce(join(repoRoot, "AGENTS.md"), repositoryAgentsTemplate({ displayName }));
    writeFileOnce(join(repoRoot, "LICENSE"), repositoryLicenseTemplate());
    writeFileOnce(join(repoRoot, "package.json"), repositoryPackageJsonTemplate({ repoName }));
    writeFileOnce(join(repoRoot, "aift-manifest.json"), repositoryManifestTemplate({ repoName, displayName }));
    writeFileOnce(join(repoRoot, ".gitignore"), repositoryGitignoreTemplate());
    writeFileOnce(join(repoRoot, "docs/.gitkeep"), "");
    writeFileOnce(join(repoRoot, "apps/.gitkeep"), "");
    writeFileOnce(join(repoRoot, "packages/.gitkeep"), "");
    writeFileOnce(join(repoRoot, "scripts/.gitkeep"), "");

    ok(`Generated repository scaffold: ${repoName}`);
    console.log("");
    console.log("Next:");
    console.log(`  cd ${repoRoot}`);
    console.log("  git init");
    console.log("  git add .");
    console.log(`  git commit -m "Initialize ${displayName}"`);
    return;
  }

'''
    text = text.replace(marker, insert + marker)

if 'console.log("  repository");' not in text:
    text = text.replace(
        'console.log("  package");',
        'console.log("  package");\n  console.log("  repository");'
    )

p.write_text(text)
PY

echo "✅ Repository generator added."
echo ""
echo "Test with a safe demo repo:"
echo "  aift-forge generate repository demo-federation-repo"
