#!/data/data/com.termux/files/usr/bin/bash
set -e

echo "📦 Adding Forge package generator"

mkdir -p packages/forge-core/src/templates

cat > packages/forge-core/src/templates/package-template.mjs <<'JS'
export function packageJsonTemplate({ packageName }) {
  return JSON.stringify(
    {
      name: `@aift/${packageName}`,
      version: "0.1.0",
      private: true,
      type: "module",
      main: "src/index.mjs",
      scripts: {
        test: "node --test"
      }
    },
    null,
    2
  ) + "\n";
}

export function packageReadmeTemplate({ displayName }) {
  return `# ${displayName}

Generated by AIFT Forge.

## Status

Foundation scaffold.

## Purpose

Describe this package's role in the federation here.
`;
}

export function packageIndexTemplate({ exportName }) {
  return `export const ${exportName} = {
  name: "${exportName}",
  status: "foundation"
};
`;
}

export function packageTestTemplate({ exportName, packageName }) {
  return `import test from "node:test";
import assert from "node:assert/strict";
import { ${exportName} } from "../src/index.mjs";

test("${packageName} exports foundation object", () => {
  assert.equal(${exportName}.status, "foundation");
});
`;
}
JS

python - <<'PY'
from pathlib import Path

p = Path("packages/forge-core/src/commands/generate.mjs")
text = p.read_text()

if 'packageJsonTemplate' not in text:
    last_imports = [line for line in text.splitlines() if line.startswith("import ")]
    last = last_imports[-1]
    text = text.replace(
        last,
        last + '\nimport { packageJsonTemplate, packageReadmeTemplate, packageIndexTemplate, packageTestTemplate } from "../templates/package-template.mjs";'
    )

if 'function toExportName' not in text:
    insert = r'''
function toExportName(name) {
  const camel = toCamelCase(name);
  return camel.charAt(0).toLowerCase() + camel.slice(1);
}

'''
    text = text.replace("function commandTemplate", insert + "function commandTemplate")

if 'if (type === "package")' not in text:
    marker = '  if (type === "model") {'
    insert = r'''  if (type === "package") {
    const packageName = toKebabCase(name);
    const displayName = toPascalCase(name);
    const exportName = toExportName(name);
    const packageRoot = join(paths.repoRoot, "packages", packageName);

    section("Generate Package");
    console.log(`Package: ${packageName}`);
    console.log(`Path: ${packageRoot}`);

    writeFileOnce(join(packageRoot, "package.json"), packageJsonTemplate({ packageName }));
    writeFileOnce(join(packageRoot, "README.md"), packageReadmeTemplate({ displayName }));
    writeFileOnce(join(packageRoot, "src/index.mjs"), packageIndexTemplate({ exportName }));
    writeFileOnce(join(packageRoot, "tests/index.test.mjs"), packageTestTemplate({ exportName, packageName }));

    ok(`Generated package: ${packageName}`);
    console.log("");
    console.log("Test with:");
    console.log(`  cd packages/${packageName}`);
    console.log("  npm test");
    return;
  }

'''
    text = text.replace(marker, insert + marker)

if 'console.log("  package");' not in text:
    text = text.replace(
        'console.log("  model");',
        'console.log("  model");\n  console.log("  package");'
    )

p.write_text(text)
PY

echo "✅ Package generator added."
echo ""
echo "Test:"
echo "  aift-forge generate package wallet-core"
