#!/data/data/com.termux/files/usr/bin/bash
set -e
cd "/data/data/com.termux/files/home/Projects/AIFT/AIFT-Forge"
exec node "/data/data/com.termux/files/home/Projects/AIFT/AIFT-Forge/packages/forge-core/src/cli/index.mjs" "$@"
