import { join } from "node:path";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { getForgePaths } from "../lib/paths.mjs";
import { section, ok, fail } from "../lib/logger.mjs";

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function writeFileIfMissing(path, content) {
  if (existsSync(path)) return false;
  ensureDir(join(path, ".."));
  writeFileSync(path, content);
  return true;
}

function bootstrapBookSmithOs(paths) {
  const osRoot = join(paths.aiftRoot, "BookSmith-Federation-OS");

  if (!existsSync(osRoot)) {
    fail(`BookSmith-Federation-OS not found at ${osRoot}`);
    process.exit(1);
  }

  section("BookSmith Federation OS");

  const dirs = [
    "apps/web-os/app/api/booksmith/run",
    "apps/web-os/components",
    "apps/web-os/lib",
    "apps/marketplace",
    "apps/node-agent",
    "packages/federation-core/src",
    "packages/storage-core/src",
    "packages/marketplace-core/src",
    "packages/wallet-core/src",
    "packages/booksmith-bridge/src",
    "packages/ui/src",
    "docs/roadmaps",
    "scripts"
  ];

  for (const dir of dirs) {
    ensureDir(join(osRoot, dir));
    ok(`dir ${dir}`);
  }

  writeFileIfMissing(
    join(osRoot, "docs/roadmaps/PHASE-0.2-WEB-OS-SHELL.md"),
    `# Phase 0.2 — Web OS Shell

Generated by AIFT Forge.

## Goal

Build the first functional BookSmith Federation OS desktop shell.

## Required surfaces

- Dashboard
- App Launcher
- AI Chat Dock
- System Health
- Roadmap
- Canon Intake
- BookSmith Bridge placeholder

## Canon Rule

User paste/upload = accepted canon.

AI output = proposed patch until approved.
`
  );

  ok("BookSmith OS Phase 0.2 folder scaffold complete.");
}

export function bootstrap(args = []) {
  const target = args[0];
  const name = args[1] ?? "booksmith";
  const paths = getForgePaths(import.meta.url);

  if (target !== "os") {
    console.log("Usage:");
    console.log("  aift-forge bootstrap os booksmith");
    process.exit(1);
  }

  if (name !== "booksmith") {
    fail(`Unknown OS bootstrap target: ${name}`);
    process.exit(1);
  }

  console.log("🖥️ AIFT Forge Bootstrap OS");
  bootstrapBookSmithOs(paths);
}
