import { join } from "node:path";
import { getForgePaths } from "../lib/paths.mjs";
import { ForgeCodegenEngine } from "../codegen/engine.mjs";
import { section, ok, warn } from "../lib/logger.mjs";

export function codegen(args = []) {
  const action = args[0] ?? "help";
  const id = args[1] ?? "sample-panel";

  const paths = getForgePaths(import.meta.url);
  const targetRepository = "BookSmith-Federation-OS";
  const webRoot = join(paths.aiftRoot, targetRepository, "apps/web-os");
  const engine = new ForgeCodegenEngine({ webRoot });

  if (action === "feature") {
    console.log("🏗️ Forge Codegen");

    const result = engine.generateFeature({
      id,
      title: id
        .split("-")
        .map((part) => part[0].toUpperCase() + part.slice(1))
        .join(" "),
      description: `Generated ${id} surface.`,
      records: [
        {
          id: "local",
          label: "Local-first",
          value: "enabled",
          description: "Generated by Forge codegen."
        }
      ]
    });

    section("Generated Files");

    for (const item of result) {
      if (item.ok && item.unchanged) ok(`unchanged ${item.path}`);
      else if (item.ok) ok(item.path);
      else warn(`${item.path} skipped: ${item.reason}`);
    }

    return;
  }

  console.log("Forge Codegen");
  console.log("");
  console.log("Usage:");
  console.log("  aift-forge codegen feature example-panel");
}

export default codegen;
